#!/bin/bash

echo "+====================================================="
echo "| Container $HOSTNAME is RUNNING"
echo "+====================================================="

while true; do
    echo "$HOSTNAME ($SX_ID:$SX_VERSION) is running ..."
    sleep 10
done