#!/bin/bash

echoNotVerbose "Execute source code runtime"
echoVerbose ""
echoVerbose "+====================================================="
echoVerbose "Execute source code runtime"
echoVerbose "+====================================================="

while true; do
    echo "$HOSTNAME ($SX_ID:$SX_VERSION) is running ..."
    sleep 10
done