#!/bin/bash -e
#
# Source code assemble script complementary to the application server assemble script provided by STARTX.
# This script will run after the middleware assembling and before publishing the resulting image
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

# app could be found in $APP_PATH
echo "this is the source code assemble hook"
exit 0;
# if you want to fail the post-build hook, exit with error code > 0