#!/bin/bash -e
#
# Source code post-deploy script complementary to the application server post-deploy script provided by STARTX.
# This script will be executed after the deployement of a new container (or pod)
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

/bin/sx post-deploy