#!/bin/bash -e
#
# Source code run script. Will replace the default container entrypoint script provided by STARTX.
# This script will run on container startup
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

while true; do
    echo "$HOSTNAME is a live example running $SX_ID:$SX_VERSION"
    sleep 10
done