#!/bin/bash -e
#
# Source code run script. Will replace the default container entrypoint script provided by STARTX.
# This script will run on container startup
#
# For more information refer to the documentation:
#  https://github.com/startxfr/docker-images
#

# app could be found in $APP_PATH
echo "this is the source code run script"
while true; do
    echo "$HOSTNAME ($SX_ID:$SX_VERSION) is running ..."
    sleep 10
done